# Read Only RBAC + IAM Policy
# https://blog.devops.dev/how-to-create-read-only-user-in-eks-cluster-fd55fe0d4ed9
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: read-only

rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - pods
  - pods/log
  - configmaps
  - secrets
  - services
  - virtualservices
  - horizontalpodautoscalers
  - gateways
  - namespaces
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: read-only-bind

subjects:
- kind: Group
  name: read-only-group
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: read-only
  apiGroup: rbac.authorization.k8s.io